Sign up and then log in. 
Depending on what exam you signed up for, a list of quizzes related to your exam will populate the homepage. 
Click on a subject card to start a quiz, where you will be given 10 questions related to the given topic. 
you'll be have 60 seconds for each question, if the timer runs out it will automatically move on to the next problem.
You'll be given a final score at the end of the test and depending on how well you did you may make it on to the high score page.
If you wish to change your exam, go to the profile page and edit what exam you wish to take.
